# Generated by Django 5.0.1 on 2024-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
