# Generated by Django 5.0.1 on 2024-01-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_systemmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmodel',
            name='google_code',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='systemmodel',
            name='web_title',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
