# Generated by Django 5.0.1 on 2024-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notificationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
