# Generated by Django 5.0.1 on 2024-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notificationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcategorymodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
