# Generated by Django 5.0.1 on 2024-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notificationcategorymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcategorymodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
