# Generated by Django 5.0.1 on 2024-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationcategorymodel_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcategorymodel',
            name='read',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
