# Generated by Django 5.0.1 on 2024-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
    ]
