# Generated by Django 5.0.1 on 2024-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
