# Generated by Django 5.0.1 on 2024-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read_noti',
            field=models.BooleanField(default=False),
        ),
    ]
