# Generated by Django 5.0.1 on 2024-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.TextField(default='2024-01-18'),
        ),
    ]
