# Generated by Django 5.0.1 on 2024-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2024-01-19 00:04:09'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.TextField(default='2024-01-19'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-19 00:04:09'),
        ),
    ]
