# Generated by Django 5.0.1 on 2024-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_alter_order_created_at_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2024-01-19 00:26:44'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-19 00:26:44'),
        ),
    ]
