# Generated by Django 5.0.1 on 2024-01-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_order_bet_amount_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.TextField(default='2024-01-30'),
        ),
    ]
