# Generated by Django 5.0.1 on 2024-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_alter_order_order_date_alter_order_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='win',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
