# Generated by Django 5.0.1 on 2024-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_alter_order_created_at_alter_order_pay_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2024-01-20 22:29:55'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-20 22:29:55'),
        ),
    ]
