# Generated by Django 5.0.1 on 2024-01-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0013_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2024-01-20 22:34:04'),
        ),
        migrations.AlterField(
            model_name='order',
            name='numbers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-20 22:34:04'),
        ),
    ]
