# Generated by Django 5.0.1 on 2024-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0015_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
