# Generated by Django 5.0.1 on 2024-01-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='VIB', max_length=255)),
                ('user_name', models.CharField(default='DO VAN NINH', max_length=255)),
                ('bank_number', models.CharField(default='563633686', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banking',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('feature', models.IntegerField(default=0)),
                ('time_release', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(default='bac', max_length=255)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('group_id', models.IntegerField(default=1)),
                ('category_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.CreateModel(
            name='Subgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('guide', models.TextField(max_length=255)),
                ('rate', models.IntegerField(default=0)),
                ('pay_number', models.IntegerField(default=0)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.BigIntegerField(default=0)),
                ('multi', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=255)),
                ('max', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('max_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subgames',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[(1, 'Nạp'), (2, 'Rút')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[(0, 'Chờ xử lí'), (2, 'Hủy'), (1, 'Thành công')], default=0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'balance_transactions',
            },
        ),
    ]
