# Generated by Django 5.0.1 on 2024-01-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banking',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='banking',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
    ]
