# Generated by Django 5.0.1 on 2024-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_release',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
