# Generated by Django 5.0.1 on 2024-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_city_created_at_alter_city_time_release_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Subgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('guide', models.TextField(max_length=255)),
                ('rate', models.IntegerField(default=0)),
                ('pay_number', models.IntegerField(default=0)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.BigIntegerField(default=0)),
                ('multi', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255)),
                ('max', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('max_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'subgame',
            },
        ),
    ]
