# Generated by Django 5.0.1 on 2024-01-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('server', '0002_remove_banking_bank_name_banking_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='bank_number',
            field=models.CharField(default='563633686', max_length=255),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='user_name',
            field=models.CharField(default='DO VAN NINH', max_length=255),
        ),
    ]
