# Generated by Django 5.0.1 on 2024-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_game_subgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgame',
            name='multi',
            field=models.IntegerField(default=0),
        ),
    ]
