# Generated by Django 5.0.1 on 2024-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_subgame_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.CharField(default='bac', max_length=255),
        ),
    ]
