# Generated by Django 5.0.1 on 2024-01-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_rate_alter_game_table_alter_subgame_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'banking',
            },
        ),
    ]
