# Generated by Django 5.0.1 on 2024-01-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_subgame_created_at_alter_subgame_updated_at'),
        ('server', '0006_game_created_at_game_status_game_updated_at_and_more'),
    ]

    operations = [
    ]
