# Generated by Django 5.0.1 on 2024-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_banking'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='user_name',
            field=models.CharField(default='DO VAN NINH', max_length=255),
        ),
        migrations.AlterField(
            model_name='banking',
            name='bank_name',
            field=models.CharField(default='VIB', max_length=255),
        ),
        migrations.AlterField(
            model_name='banking',
            name='bank_number',
            field=models.CharField(default='563633686', max_length=255),
        ),
    ]
