# Generated by Django 5.0.1 on 2024-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_merge_20240124_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgame',
            name='guide',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='subgame',
            name='max_amount',
            field=models.BigIntegerField(default=10000000000),
        ),
        migrations.AlterField(
            model_name='subgame',
            name='min_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
