# Generated by Django 5.0.1 on 2024-01-18 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_banking_user_name_alter_banking_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banking',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
