# Generated by Django 5.0.1 on 2024-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_balancetransaction_bank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgame',
            name='rate',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
