# Generated by Django 5.0.1 on 2024-01-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_banking_created_at_banking_status_banking_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Nap', 'Nạp'), ('Rut', 'Rút')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Chờ xử lí'), ('Cancel', 'Hủy'), ('Approved', 'Thành công')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'balance_transactions',
            },
        ),
    ]
