# Generated by Django 5.0.1 on 2024-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_balancetransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='status',
            field=models.CharField(choices=[(0, 'Chờ xử lí'), (2, 'Hủy'), (1, 'Thành công')], default=0, max_length=20),
        ),
    ]
